# Generated by Django 5.2.1 on 2025-05-31 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.CharField(default='https://via.placeholder.com/50', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('image', 'Image')], default='text', max_length=10)),
                ('delay', models.IntegerField(default=3000)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.participant')),
            ],
        ),
    ]
