# Generated by Django 5.2.1 on 2025-05-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='avatar',
            field=models.CharField(default='/static/chat_app/images/avatar.png', max_length=255),
        ),
    ]
