# Generated by Django 5.2.1 on 2025-06-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_alter_participant_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
